AWSTemplateFormatVersion: '2010-09-09'
Description: 'Sample template for S3 bucket'

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket
    Default: my-sample-bucket

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Environment
          Value: Development

Outputs:
  BucketArn:
    Description: ARN of the S3 bucket
    Value: !GetAtt MyS3Bucket.Arn
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref MyS3Bucket
